apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-core
  namespace: lakeside
  labels:
    app: customer-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-core
  template:
    metadata:
      labels:
        app: customer-core
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - env:
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: http://spring-boot-admin:9000
          image: 063725538836.dkr.ecr.eu-central-1.amazonaws.com/customer-core:latest
          imagePullPolicy: Always
          name: customer-core
          ports:
            - containerPort: 8110
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: customer-core
  namespace: lakeside
spec:
  selector:
    app: customer-core
  ports:
    - name: "8110"
      port: 8110
      targetPort: 8110
  type: LoadBalancer
