apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management-backend
  namespace: lakeside
  labels:
    app: customer-management-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-management-backend
  template:
    metadata:
      labels:
        app: customer-management-backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - env:
            - name: CUSTOMERCORE_BASEURL
              value: http://customer-core:8110
            - name: SPRING_BOOT_ADMIN_CLIENT_URL
              value: http://spring-boot-admin:9000
          image: 063725538836.dkr.ecr.eu-central-1.amazonaws.com/customer-management-backend:latest
          imagePullPolicy: Always
          name: customer-management-backend
          ports:
            - containerPort: 8100
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: customer-management-backend
  namespace: lakeside
spec:
  selector:
    app: customer-management-backend
  ports:
    - name: "8100"
      port: 8100
      targetPort: 8100
  type: LoadBalancer
#  loadBalancerIP: 34.65.192.94
